name: Rename Folders and Commit to UPM Branch

on:
  push:
    branches:
      - main  # main 브랜치에 커밋이 발생할 때 이 워크플로우가 실행됩니다.

jobs:
  rename-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.RENAME_PAT }}
        fetch-depth: 0

    - name: Setup Git Config
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Create local UPM branch
      run: |
        git checkout -b upm || git checkout upm

    - name: Rename folders
      run: |
        mv Assets/01_Scenes Assets/01_Scenes~
        mv Assets/02_Scripts Assets/02_Scripts~
        mv Assets/03_Prefabs Assets/03_Prefabs~
        mv Assets/04_Sources Assets/04_Sources~
        mv Assets/05_Sounds Assets/05_Sounds~
        mv Assets/06_Animations Assets/06_Animations~
        mv Assets/07_TestAssets Assets/07_TestAssets~
        mv Assets/OriginalAssets Assets/OriginalAssets~
        mv Assets/Resources Assets/Resources~
        mv Assets/ThirdPartyTools Assets/ThirdPartyTools~

    - name: delete meta files
      run: |
        rm -rf Assets/00_Assets Assets/00_Assets.meta
        rm -rf Assets/00_Test Assets/00_Test.meta
        rm -rf Assets/01_Scenes Assets/01_Scenes.meta
        rm -rf Assets/02_Scripts Assets/02_Scripts.meta
        rm -rf Assets/03_Prefabs Assets/03_Prefabs.meta
        rm -rf Assets/04_Sources Assets/04_Sources.meta
        rm -rf Assets/05_Sounds Assets/05_Sounds.meta
        rm -rf Assets/06_Animations Assets/06_Animations.meta
        rm -rf Assets/07_TestAssets Assets/07_TestAssets.meta
        rm -rf Assets/OriginalAssets Assets/OriginalAssets.meta
        rm -rf Assets/Resources Assets/Resources.meta
        rm -rf Assets/ThirdPartyTools Assets/ThirdPartyTools.meta

    - name: Commit changes
      run: |
        git add .
        git commit -m "Renamed folders as per new structure"

    - name: Force push changes to UPM branch
      run: |
          git push -u origin upm -f
      env:
        GITHUB_TOKEN: ${{ secrets.RENAME_PAT }}
